# Generated by Django 3.2.5 on 2021-07-16 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.class', verbose_name='Lop'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
    ]
