# Generated by Django 3.2.5 on 2021-07-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_alter_subject_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khoa',
            name='department',
            field=models.CharField(error_messages={'unique': 'Khoa nay da ton tai'}, max_length=40, unique=True, verbose_name='Ten khoa'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject',
            field=models.CharField(error_messages={'unique': 'Mon hoc nay da ton tai'}, max_length=40, unique=True, verbose_name='Ten mon hoc'),
        ),
    ]
