# Generated by Django 3.2.5 on 2021-07-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_auto_20210714_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_unit',
            field=models.IntegerField(blank=True, null=True, verbose_name='So tiet hoc'),
        ),
    ]
